# inventory file
all:
  children:
    server:
      hosts:
        my-pc: # my computer for testing 
          ansible_host: localhost
          ansible_connection: local
    workers:
      hosts:
        raspberry-pi:
          ansible_host: <ip-address>
          ansible_user: dietpi
          ansible_ssh_private_key_file: ~/.ssh/xxx