# inventory file
all:
  children:
    server:
      hosts:
        my-pc: # my computer for testing 
          ansible_host: localhost
          ansible_connection: local
    workers:
      hosts:
        raspberry-pi:
          ansible_host: 192.168.50.196