---
- name: testing server
  hosts: server
  tasks:
    - name: ping server
      ansible.builtin.ping:

    - name: import vars
      include_vars:
        file: ansible/inventory/group_vars/server.yml
        

    - name: print msg
      ansible.builtin.debug:
        msg: "hello from server, java home is {{ }}"

- name: testing rpi
  hosts: workers
  tasks:
    - name: ping worker
      ansible.builtin.ping: 

    - name: print msg
      ansible.builtin.debug:
        msg: hi from worker # {{ inventory_hostname }} # check that this works 